/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        'light-neutral': {
          primary: '#3f3f46',
          'primary-content': '#ffffff',
          secondary: '#71717a',
          'secondary-content': '#ffffff',
          accent: '#52525b',
          'accent-content': '#ffffff',
          neutral: '#3f3f46',
          'neutral-content': '#f4f4f5',
          'base-100': '#ffffff',
          'base-200': '#f5f5f7',
          'base-300': '#d4d4d8',
          'base-content': '#27272a',
          info: '#64748b',
          'info-content': '#ffffff',
          success: '#6e8b78',
          'success-content': '#ffffff',
          warning: '#b39468',
          'warning-content': '#1f2937',
          error: '#a86b66',
          'error-content': '#ffffff',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.375rem',
          '--rounded-badge': '0.375rem',
        },
      },
      {
        'dark-neutral': {
          primary: '#d4d4d8',
          'primary-content': '#18181b',
          secondary: '#a1a1aa',
          'secondary-content': '#18181b',
          accent: '#e5e5e5',
          'accent-content': '#171717',
          neutral: '#737373',
          'neutral-content': '#f5f5f5',
          'base-100': '#262626',
          'base-200': '#1a1a1a',
          'base-300': '#404040',
          'base-content': '#e5e5e5',
          info: '#94a3b8',
          'info-content': '#111827',
          success: '#86a58f',
          'success-content': '#102017',
          warning: '#c8a978',
          'warning-content': '#241a08',
          error: '#c1847d',
          'error-content': '#2a1010',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.375rem',
          '--rounded-badge': '0.375rem',
        },
      },
    ],
    logs: false,
  },
}
