package merge

// CountryInfo describes one country/region entry from the source COUNTRY_MAP.
type CountryInfo struct {
	Code    string
	Name    string
	Emoji   string
	Aliases []string
}

// countryOrder preserves the declaration order of COUNTRY_MAP in merge.js.
// Order matters for the emoji-scan pass in extractCountry, which iterates the
// map and takes the first emoji found in the tag.
var countryOrder = []string{
	"HK", "CN", "US", "JP", "SG", "TW", "KR", "GB", "DE", "CA", "AU", "FR", "NL",
	"IN", "RU", "BR", "AR", "TR", "TH", "MY", "PH", "VN", "ID", "IT", "ES", "CH",
	"SE", "NO", "FI", "PL", "AT", "BE", "DK", "PT", "GR", "IE", "CZ", "RO", "UA",
	"LT", "LV", "EE", "BG", "HR", "SK", "SI", "HU", "IL", "AE", "SA", "KW", "PK",
	"BD", "KZ", "UZ", "MX", "CL", "CO", "PE", "VE", "ZA", "EG", "NG", "NZ", "FJ",
	"AC", "AD", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AS", "AW", "AX", "AZ",
	"BA", "BB", "BF", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BS", "BT",
	"BV", "BW", "BY", "BZ", "CC", "CD", "CF", "CG", "CI", "CK", "CM", "CP", "CQ",
	"CR", "CU", "CV", "CW", "CX", "CY", "DG", "DJ", "DM", "DO", "DZ", "EA", "EC",
	"EH", "ER", "ET", "EU", "FK", "FM", "FO", "GA", "GD", "GE", "GF", "GG", "GH",
	"GI", "GL", "GM", "GN", "GP", "GQ", "GS", "GT", "GU", "GW", "GY", "HM", "HN",
	"HT", "IC", "IM", "IO", "IQ", "IR", "IS", "JE", "JM", "JO", "KE", "KG", "KH",
	"KI", "KM", "KN", "KP", "KY", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LU",
	"LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO",
	"MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MZ", "NA", "NC", "NE", "NF",
	"NI", "NP", "NR", "NU", "OM", "PA", "PF", "PG", "PM", "PN", "PR", "PS", "PW",
	"PY", "QA", "RE", "RS", "RW", "SB", "SC", "SD", "SH", "SJ", "SL", "SM", "SN",
	"SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ", "TA", "TC", "TD", "TF", "TG",
	"TJ", "TK", "TL", "TM", "TN", "TO", "TT", "TV", "TZ", "UG", "UM", "UN", "UY",
	"VA", "VC", "VG", "VI", "VU", "WF", "WS", "XK", "YE", "YT", "ZM", "ZW",
}

// standardCountryInfo builds catalog entries added after the original merge.js
// country set. Text detection uses the English and Chinese names; uppercase
// two-letter code tokens are handled separately to avoid matching ordinary
// lowercase words such as "to", "in" and "is".
func standardCountryInfo(code, name, localizedName string) CountryInfo {
	emoji := buildFlagEmoji(code)
	return CountryInfo{
		Code:    code,
		Name:    name,
		Emoji:   emoji,
		Aliases: []string{name, localizedName, emoji},
	}
}

// countryMap keeps the original merge.js entries byte-compatible and extends
// them with every Unicode Emoji 17.0 RGI two-letter flag sequence.
var countryMap = map[string]CountryInfo{
	"HK": {"HK", "Hong Kong", "🇭🇰", []string{"香港", "hongkong", "hk", "🇭🇰"}},
	"CN": {"CN", "China", "🇨🇳", []string{"中国", "china", "cn", "🇨🇳"}},
	"US": {"US", "United States", "🇺🇸", []string{"美国", "unitedstates", "america", "us", "🇺🇸"}},
	"JP": {"JP", "Japan", "🇯🇵", []string{"日本", "japan", "jp", "🇯🇵"}},
	"SG": {"SG", "Singapore", "🇸🇬", []string{"新加坡", "singapore", "sg", "🇸🇬"}},
	"TW": {"TW", "Taiwan", "🇹🇼", []string{"台湾", "taiwan", "tw", "🇹🇼"}},
	"KR": {"KR", "South Korea", "🇰🇷", []string{"韩国", "korea", "kr", "🇰🇷"}},
	"GB": {"GB", "United Kingdom", "🇬🇧", []string{"英国", "uk", "britain", "gb", "🇬🇧"}},
	"DE": {"DE", "Germany", "🇩🇪", []string{"德国", "germany", "de", "🇩🇪"}},
	"CA": {"CA", "Canada", "🇨🇦", []string{"加拿大", "canada", "ca", "🇨🇦"}},
	"AU": {"AU", "Australia", "🇦🇺", []string{"澳大利亚", "australia", "au", "🇦🇺"}},
	"FR": {"FR", "France", "🇫🇷", []string{"法国", "france", "fr", "🇫🇷"}},
	"NL": {"NL", "Netherlands", "🇳🇱", []string{"荷兰", "netherlands", "nl", "🇳🇱"}},
	"IN": {"IN", "India", "🇮🇳", []string{"印度", "india", "in", "🇮🇳"}},
	"RU": {"RU", "Russia", "🇷🇺", []string{"俄罗斯", "russia", "ru", "🇷🇺"}},
	"BR": {"BR", "Brazil", "🇧🇷", []string{"巴西", "brazil", "br", "🇧🇷"}},
	"AR": {"AR", "Argentina", "🇦🇷", []string{"阿根廷", "argentina", "ar", "🇦🇷"}},
	"TR": {"TR", "Turkey", "🇹🇷", []string{"土耳其", "turkey", "tr", "🇹🇷"}},
	"TH": {"TH", "Thailand", "🇹🇭", []string{"泰国", "thailand", "th", "🇹🇭"}},
	"MY": {"MY", "Malaysia", "🇲🇾", []string{"马来西亚", "malaysia", "my", "🇲🇾"}},
	"PH": {"PH", "Philippines", "🇵🇭", []string{"菲律宾", "philippines", "ph", "🇵🇭"}},
	"VN": {"VN", "Vietnam", "🇻🇳", []string{"越南", "vietnam", "vn", "🇻🇳"}},
	"ID": {"ID", "Indonesia", "🇮🇩", []string{"印度尼西亚", "印尼", "indonesia", "id", "🇮🇩"}},
	"IT": {"IT", "Italy", "🇮🇹", []string{"意大利", "italy", "it", "🇮🇹"}},
	"ES": {"ES", "Spain", "🇪🇸", []string{"西班牙", "spain", "es", "🇪🇸"}},
	"CH": {"CH", "Switzerland", "🇨🇭", []string{"瑞士", "switzerland", "ch", "🇨🇭"}},
	"SE": {"SE", "Sweden", "🇸🇪", []string{"瑞典", "sweden", "se", "🇸🇪"}},
	"NO": {"NO", "Norway", "🇳🇴", []string{"挪威", "norway", "no", "🇳🇴"}},
	"FI": {"FI", "Finland", "🇫🇮", []string{"芬兰", "finland", "fi", "🇫🇮"}},
	"PL": {"PL", "Poland", "🇵🇱", []string{"波兰", "poland", "pl", "🇵🇱"}},
	"AT": {"AT", "Austria", "🇦🇹", []string{"奥地利", "austria", "at", "🇦🇹"}},
	"BE": {"BE", "Belgium", "🇧🇪", []string{"比利时", "belgium", "be", "🇧🇪"}},
	"DK": {"DK", "Denmark", "🇩🇰", []string{"丹麦", "denmark", "dk", "🇩🇰"}},
	"PT": {"PT", "Portugal", "🇵🇹", []string{"葡萄牙", "portugal", "pt", "🇵🇹"}},
	"GR": {"GR", "Greece", "🇬🇷", []string{"希腊", "greece", "gr", "🇬🇷"}},
	"IE": {"IE", "Ireland", "🇮🇪", []string{"爱尔兰", "ireland", "ie", "🇮🇪"}},
	"CZ": {"CZ", "Czech Republic", "🇨🇿", []string{"捷克", "czech", "cz", "🇨🇿"}},
	"RO": {"RO", "Romania", "🇷🇴", []string{"罗马尼亚", "romania", "ro", "🇷🇴"}},
	"UA": {"UA", "Ukraine", "🇺🇦", []string{"乌克兰", "ukraine", "ua", "🇺🇦"}},
	"LT": {"LT", "Lithuania", "🇱🇹", []string{"立陶宛", "lithuania", "lt", "🇱🇹"}},
	"LV": {"LV", "Latvia", "🇱🇻", []string{"拉脱维亚", "latvia", "lv", "🇱🇻"}},
	"EE": {"EE", "Estonia", "🇪🇪", []string{"爱沙尼亚", "estonia", "ee", "🇪🇪"}},
	"BG": {"BG", "Bulgaria", "🇧🇬", []string{"保加利亚", "bulgaria", "bg", "🇧🇬"}},
	"HR": {"HR", "Croatia", "🇭🇷", []string{"克罗地亚", "croatia", "hr", "🇭🇷"}},
	"SK": {"SK", "Slovakia", "🇸🇰", []string{"斯洛伐克", "slovakia", "sk", "🇸🇰"}},
	"SI": {"SI", "Slovenia", "🇸🇮", []string{"斯洛文尼亚", "slovenia", "si", "🇸🇮"}},
	"HU": {"HU", "Hungary", "🇭🇺", []string{"匈牙利", "hungary", "hu", "🇭🇺"}},
	"IL": {"IL", "Israel", "🇮🇱", []string{"以色列", "israel", "il", "🇮🇱"}},
	"AE": {"AE", "United Arab Emirates", "🇦🇪", []string{"阿联酋", "uae", "emirates", "ae", "🇦🇪"}},
	"SA": {"SA", "Saudi Arabia", "🇸🇦", []string{"沙特", "沙特阿拉伯", "saudi", "sa", "🇸🇦"}},
	"KW": {"KW", "Kuwait", "🇰🇼", []string{"科威特", "kuwait", "kw", "🇰🇼"}},
	"PK": {"PK", "Pakistan", "🇵🇰", []string{"巴基斯坦", "pakistan", "pk", "🇵🇰"}},
	"BD": {"BD", "Bangladesh", "🇧🇩", []string{"孟加拉", "孟加拉国", "bangladesh", "bd", "🇧🇩"}},
	"KZ": {"KZ", "Kazakhstan", "🇰🇿", []string{"哈萨克斯坦", "kazakhstan", "kz", "🇰🇿"}},
	"UZ": {"UZ", "Uzbekistan", "🇺🇿", []string{"乌兹别克斯坦", "uzbekistan", "uz", "🇺🇿"}},
	"MX": {"MX", "Mexico", "🇲🇽", []string{"墨西哥", "mexico", "mx", "🇲🇽"}},
	"CL": {"CL", "Chile", "🇨🇱", []string{"智利", "chile", "cl", "🇨🇱"}},
	"CO": {"CO", "Colombia", "🇨🇴", []string{"哥伦比亚", "colombia", "co", "🇨🇴"}},
	"PE": {"PE", "Peru", "🇵🇪", []string{"秘鲁", "peru", "pe", "🇵🇪"}},
	"VE": {"VE", "Venezuela", "🇻🇪", []string{"委内瑞拉", "venezuela", "ve", "🇻🇪"}},
	"ZA": {"ZA", "South Africa", "🇿🇦", []string{"南非", "southafrica", "za", "🇿🇦"}},
	"EG": {"EG", "Egypt", "🇪🇬", []string{"埃及", "egypt", "eg", "🇪🇬"}},
	"NG": {"NG", "Nigeria", "🇳🇬", []string{"尼日利亚", "nigeria", "ng", "🇳🇬"}},
	"NZ": {"NZ", "New Zealand", "🇳🇿", []string{"新西兰", "newzealand", "nz", "🇳🇿"}},
	"FJ": {"FJ", "Fiji", "🇫🇯", []string{"斐济", "fiji", "fj", "🇫🇯"}},
	"AC": standardCountryInfo("AC", "Ascension Island", "阿森松岛"),
	"AD": standardCountryInfo("AD", "Andorra", "安道尔"),
	"AF": standardCountryInfo("AF", "Afghanistan", "阿富汗"),
	"AG": standardCountryInfo("AG", "Antigua & Barbuda", "安提瓜和巴布达"),
	"AI": standardCountryInfo("AI", "Anguilla", "安圭拉"),
	"AL": standardCountryInfo("AL", "Albania", "阿尔巴尼亚"),
	"AM": standardCountryInfo("AM", "Armenia", "亚美尼亚"),
	"AO": standardCountryInfo("AO", "Angola", "安哥拉"),
	"AQ": standardCountryInfo("AQ", "Antarctica", "南极洲"),
	"AS": standardCountryInfo("AS", "American Samoa", "美属萨摩亚"),
	"AW": standardCountryInfo("AW", "Aruba", "阿鲁巴"),
	"AX": standardCountryInfo("AX", "Åland Islands", "奥兰群岛"),
	"AZ": standardCountryInfo("AZ", "Azerbaijan", "阿塞拜疆"),
	"BA": standardCountryInfo("BA", "Bosnia & Herzegovina", "波斯尼亚和黑塞哥维那"),
	"BB": standardCountryInfo("BB", "Barbados", "巴巴多斯"),
	"BF": standardCountryInfo("BF", "Burkina Faso", "布基纳法索"),
	"BH": standardCountryInfo("BH", "Bahrain", "巴林"),
	"BI": standardCountryInfo("BI", "Burundi", "布隆迪"),
	"BJ": standardCountryInfo("BJ", "Benin", "贝宁"),
	"BL": standardCountryInfo("BL", "St. Barthélemy", "圣巴泰勒米"),
	"BM": standardCountryInfo("BM", "Bermuda", "百慕大"),
	"BN": standardCountryInfo("BN", "Brunei", "文莱"),
	"BO": standardCountryInfo("BO", "Bolivia", "玻利维亚"),
	"BQ": standardCountryInfo("BQ", "Caribbean Netherlands", "荷属加勒比区"),
	"BS": standardCountryInfo("BS", "Bahamas", "巴哈马"),
	"BT": standardCountryInfo("BT", "Bhutan", "不丹"),
	"BV": standardCountryInfo("BV", "Bouvet Island", "布韦岛"),
	"BW": standardCountryInfo("BW", "Botswana", "博茨瓦纳"),
	"BY": standardCountryInfo("BY", "Belarus", "白俄罗斯"),
	"BZ": standardCountryInfo("BZ", "Belize", "伯利兹"),
	"CC": standardCountryInfo("CC", "Cocos (Keeling) Islands", "科科斯（基林）群岛"),
	"CD": standardCountryInfo("CD", "Congo - Kinshasa", "刚果（金）"),
	"CF": standardCountryInfo("CF", "Central African Republic", "中非共和国"),
	"CG": standardCountryInfo("CG", "Congo - Brazzaville", "刚果（布）"),
	"CI": standardCountryInfo("CI", "Côte d’Ivoire", "科特迪瓦"),
	"CK": standardCountryInfo("CK", "Cook Islands", "库克群岛"),
	"CM": standardCountryInfo("CM", "Cameroon", "喀麦隆"),
	"CP": standardCountryInfo("CP", "Clipperton Island", "克利珀顿岛"),
	"CQ": standardCountryInfo("CQ", "Sark", "萨克岛"),
	"CR": standardCountryInfo("CR", "Costa Rica", "哥斯达黎加"),
	"CU": standardCountryInfo("CU", "Cuba", "古巴"),
	"CV": standardCountryInfo("CV", "Cape Verde", "佛得角"),
	"CW": standardCountryInfo("CW", "Curaçao", "库拉索"),
	"CX": standardCountryInfo("CX", "Christmas Island", "圣诞岛"),
	"CY": standardCountryInfo("CY", "Cyprus", "塞浦路斯"),
	"DG": standardCountryInfo("DG", "Diego Garcia", "迪戈加西亚岛"),
	"DJ": standardCountryInfo("DJ", "Djibouti", "吉布提"),
	"DM": standardCountryInfo("DM", "Dominica", "多米尼克"),
	"DO": standardCountryInfo("DO", "Dominican Republic", "多米尼加共和国"),
	"DZ": standardCountryInfo("DZ", "Algeria", "阿尔及利亚"),
	"EA": standardCountryInfo("EA", "Ceuta & Melilla", "休达及梅利利亚"),
	"EC": standardCountryInfo("EC", "Ecuador", "厄瓜多尔"),
	"EH": standardCountryInfo("EH", "Western Sahara", "西撒哈拉"),
	"ER": standardCountryInfo("ER", "Eritrea", "厄立特里亚"),
	"ET": standardCountryInfo("ET", "Ethiopia", "埃塞俄比亚"),
	"EU": standardCountryInfo("EU", "European Union", "欧盟"),
	"FK": standardCountryInfo("FK", "Falkland Islands", "福克兰群岛"),
	"FM": standardCountryInfo("FM", "Micronesia", "密克罗尼西亚"),
	"FO": standardCountryInfo("FO", "Faroe Islands", "法罗群岛"),
	"GA": standardCountryInfo("GA", "Gabon", "加蓬"),
	"GD": standardCountryInfo("GD", "Grenada", "格林纳达"),
	"GE": standardCountryInfo("GE", "Georgia", "格鲁吉亚"),
	"GF": standardCountryInfo("GF", "French Guiana", "法属圭亚那"),
	"GG": standardCountryInfo("GG", "Guernsey", "根西岛"),
	"GH": standardCountryInfo("GH", "Ghana", "加纳"),
	"GI": standardCountryInfo("GI", "Gibraltar", "直布罗陀"),
	"GL": standardCountryInfo("GL", "Greenland", "格陵兰"),
	"GM": standardCountryInfo("GM", "Gambia", "冈比亚"),
	"GN": standardCountryInfo("GN", "Guinea", "几内亚"),
	"GP": standardCountryInfo("GP", "Guadeloupe", "瓜德罗普"),
	"GQ": standardCountryInfo("GQ", "Equatorial Guinea", "赤道几内亚"),
	"GS": standardCountryInfo("GS", "South Georgia & South Sandwich Islands", "南乔治亚和南桑威奇群岛"),
	"GT": standardCountryInfo("GT", "Guatemala", "危地马拉"),
	"GU": standardCountryInfo("GU", "Guam", "关岛"),
	"GW": standardCountryInfo("GW", "Guinea-Bissau", "几内亚比绍"),
	"GY": standardCountryInfo("GY", "Guyana", "圭亚那"),
	"HM": standardCountryInfo("HM", "Heard & McDonald Islands", "赫德岛和麦克唐纳群岛"),
	"HN": standardCountryInfo("HN", "Honduras", "洪都拉斯"),
	"HT": standardCountryInfo("HT", "Haiti", "海地"),
	"IC": standardCountryInfo("IC", "Canary Islands", "加纳利群岛"),
	"IM": standardCountryInfo("IM", "Isle of Man", "马恩岛"),
	"IO": standardCountryInfo("IO", "British Indian Ocean Territory", "英属印度洋领地"),
	"IQ": standardCountryInfo("IQ", "Iraq", "伊拉克"),
	"IR": standardCountryInfo("IR", "Iran", "伊朗"),
	"IS": standardCountryInfo("IS", "Iceland", "冰岛"),
	"JE": standardCountryInfo("JE", "Jersey", "泽西岛"),
	"JM": standardCountryInfo("JM", "Jamaica", "牙买加"),
	"JO": standardCountryInfo("JO", "Jordan", "约旦"),
	"KE": standardCountryInfo("KE", "Kenya", "肯尼亚"),
	"KG": standardCountryInfo("KG", "Kyrgyzstan", "吉尔吉斯斯坦"),
	"KH": standardCountryInfo("KH", "Cambodia", "柬埔寨"),
	"KI": standardCountryInfo("KI", "Kiribati", "基里巴斯"),
	"KM": standardCountryInfo("KM", "Comoros", "科摩罗"),
	"KN": standardCountryInfo("KN", "St. Kitts & Nevis", "圣基茨和尼维斯"),
	"KP": standardCountryInfo("KP", "North Korea", "朝鲜"),
	"KY": standardCountryInfo("KY", "Cayman Islands", "开曼群岛"),
	"LA": standardCountryInfo("LA", "Laos", "老挝"),
	"LB": standardCountryInfo("LB", "Lebanon", "黎巴嫩"),
	"LC": standardCountryInfo("LC", "St. Lucia", "圣卢西亚"),
	"LI": standardCountryInfo("LI", "Liechtenstein", "列支敦士登"),
	"LK": standardCountryInfo("LK", "Sri Lanka", "斯里兰卡"),
	"LR": standardCountryInfo("LR", "Liberia", "利比里亚"),
	"LS": standardCountryInfo("LS", "Lesotho", "莱索托"),
	"LU": standardCountryInfo("LU", "Luxembourg", "卢森堡"),
	"LY": standardCountryInfo("LY", "Libya", "利比亚"),
	"MA": standardCountryInfo("MA", "Morocco", "摩洛哥"),
	"MC": standardCountryInfo("MC", "Monaco", "摩纳哥"),
	"MD": standardCountryInfo("MD", "Moldova", "摩尔多瓦"),
	"ME": standardCountryInfo("ME", "Montenegro", "黑山"),
	"MF": standardCountryInfo("MF", "St. Martin", "法属圣马丁"),
	"MG": standardCountryInfo("MG", "Madagascar", "马达加斯加"),
	"MH": standardCountryInfo("MH", "Marshall Islands", "马绍尔群岛"),
	"MK": standardCountryInfo("MK", "North Macedonia", "北马其顿"),
	"ML": standardCountryInfo("ML", "Mali", "马里"),
	"MM": standardCountryInfo("MM", "Myanmar (Burma)", "缅甸"),
	"MN": standardCountryInfo("MN", "Mongolia", "蒙古"),
	"MO": standardCountryInfo("MO", "Macao SAR China", "中国澳门特别行政区"),
	"MP": standardCountryInfo("MP", "Northern Mariana Islands", "北马里亚纳群岛"),
	"MQ": standardCountryInfo("MQ", "Martinique", "马提尼克"),
	"MR": standardCountryInfo("MR", "Mauritania", "毛里塔尼亚"),
	"MS": standardCountryInfo("MS", "Montserrat", "蒙特塞拉特"),
	"MT": standardCountryInfo("MT", "Malta", "马耳他"),
	"MU": standardCountryInfo("MU", "Mauritius", "毛里求斯"),
	"MV": standardCountryInfo("MV", "Maldives", "马尔代夫"),
	"MW": standardCountryInfo("MW", "Malawi", "马拉维"),
	"MZ": standardCountryInfo("MZ", "Mozambique", "莫桑比克"),
	"NA": standardCountryInfo("NA", "Namibia", "纳米比亚"),
	"NC": standardCountryInfo("NC", "New Caledonia", "新喀里多尼亚"),
	"NE": standardCountryInfo("NE", "Niger", "尼日尔"),
	"NF": standardCountryInfo("NF", "Norfolk Island", "诺福克岛"),
	"NI": standardCountryInfo("NI", "Nicaragua", "尼加拉瓜"),
	"NP": standardCountryInfo("NP", "Nepal", "尼泊尔"),
	"NR": standardCountryInfo("NR", "Nauru", "瑙鲁"),
	"NU": standardCountryInfo("NU", "Niue", "纽埃"),
	"OM": standardCountryInfo("OM", "Oman", "阿曼"),
	"PA": standardCountryInfo("PA", "Panama", "巴拿马"),
	"PF": standardCountryInfo("PF", "French Polynesia", "法属波利尼西亚"),
	"PG": standardCountryInfo("PG", "Papua New Guinea", "巴布亚新几内亚"),
	"PM": standardCountryInfo("PM", "St. Pierre & Miquelon", "圣皮埃尔和密克隆群岛"),
	"PN": standardCountryInfo("PN", "Pitcairn Islands", "皮特凯恩群岛"),
	"PR": standardCountryInfo("PR", "Puerto Rico", "波多黎各"),
	"PS": standardCountryInfo("PS", "Palestinian Territories", "巴勒斯坦领土"),
	"PW": standardCountryInfo("PW", "Palau", "帕劳"),
	"PY": standardCountryInfo("PY", "Paraguay", "巴拉圭"),
	"QA": standardCountryInfo("QA", "Qatar", "卡塔尔"),
	"RE": standardCountryInfo("RE", "Réunion", "留尼汪"),
	"RS": standardCountryInfo("RS", "Serbia", "塞尔维亚"),
	"RW": standardCountryInfo("RW", "Rwanda", "卢旺达"),
	"SB": standardCountryInfo("SB", "Solomon Islands", "所罗门群岛"),
	"SC": standardCountryInfo("SC", "Seychelles", "塞舌尔"),
	"SD": standardCountryInfo("SD", "Sudan", "苏丹"),
	"SH": standardCountryInfo("SH", "St. Helena", "圣赫勒拿"),
	"SJ": standardCountryInfo("SJ", "Svalbard & Jan Mayen", "斯瓦尔巴和扬马延"),
	"SL": standardCountryInfo("SL", "Sierra Leone", "塞拉利昂"),
	"SM": standardCountryInfo("SM", "San Marino", "圣马力诺"),
	"SN": standardCountryInfo("SN", "Senegal", "塞内加尔"),
	"SO": standardCountryInfo("SO", "Somalia", "索马里"),
	"SR": standardCountryInfo("SR", "Suriname", "苏里南"),
	"SS": standardCountryInfo("SS", "South Sudan", "南苏丹"),
	"ST": standardCountryInfo("ST", "São Tomé & Príncipe", "圣多美和普林西比"),
	"SV": standardCountryInfo("SV", "El Salvador", "萨尔瓦多"),
	"SX": standardCountryInfo("SX", "Sint Maarten", "荷属圣马丁"),
	"SY": standardCountryInfo("SY", "Syria", "叙利亚"),
	"SZ": standardCountryInfo("SZ", "Eswatini", "斯威士兰"),
	"TA": standardCountryInfo("TA", "Tristan da Cunha", "特里斯坦-达库尼亚群岛"),
	"TC": standardCountryInfo("TC", "Turks & Caicos Islands", "特克斯和凯科斯群岛"),
	"TD": standardCountryInfo("TD", "Chad", "乍得"),
	"TF": standardCountryInfo("TF", "French Southern Territories", "法属南部领地"),
	"TG": standardCountryInfo("TG", "Togo", "多哥"),
	"TJ": standardCountryInfo("TJ", "Tajikistan", "塔吉克斯坦"),
	"TK": standardCountryInfo("TK", "Tokelau", "托克劳"),
	"TL": standardCountryInfo("TL", "Timor-Leste", "东帝汶"),
	"TM": standardCountryInfo("TM", "Turkmenistan", "土库曼斯坦"),
	"TN": standardCountryInfo("TN", "Tunisia", "突尼斯"),
	"TO": standardCountryInfo("TO", "Tonga", "汤加"),
	"TT": standardCountryInfo("TT", "Trinidad & Tobago", "特立尼达和多巴哥"),
	"TV": standardCountryInfo("TV", "Tuvalu", "图瓦卢"),
	"TZ": standardCountryInfo("TZ", "Tanzania", "坦桑尼亚"),
	"UG": standardCountryInfo("UG", "Uganda", "乌干达"),
	"UM": standardCountryInfo("UM", "U.S. Outlying Islands", "美国本土外小岛屿"),
	"UN": standardCountryInfo("UN", "United Nations", "联合国"),
	"UY": standardCountryInfo("UY", "Uruguay", "乌拉圭"),
	"VA": standardCountryInfo("VA", "Vatican City", "梵蒂冈"),
	"VC": standardCountryInfo("VC", "St. Vincent & Grenadines", "圣文森特和格林纳丁斯"),
	"VG": standardCountryInfo("VG", "British Virgin Islands", "英属维尔京群岛"),
	"VI": standardCountryInfo("VI", "U.S. Virgin Islands", "美属维尔京群岛"),
	"VU": standardCountryInfo("VU", "Vanuatu", "瓦努阿图"),
	"WF": standardCountryInfo("WF", "Wallis & Futuna", "瓦利斯和富图纳"),
	"WS": standardCountryInfo("WS", "Samoa", "萨摩亚"),
	"XK": standardCountryInfo("XK", "Kosovo", "科索沃"),
	"YE": standardCountryInfo("YE", "Yemen", "也门"),
	"YT": standardCountryInfo("YT", "Mayotte", "马约特"),
	"ZM": standardCountryInfo("ZM", "Zambia", "赞比亚"),
	"ZW": standardCountryInfo("ZW", "Zimbabwe", "津巴布韦"),
}
